# .nixpacks.toml - Optimized for Railway deployment
[variables]
NODE_ENV = "production"
NPM_CONFIG_FUND = "false"
NPM_CONFIG_AUDIT = "false"
NPM_CONFIG_UPDATE_NOTIFIER = "false"

[phases.setup]
nixPkgs = ["nodejs_18"]

[phases.install]
cmds = [
  "npm config set fund false",
  "npm config set audit false", 
  "npm config set update-notifier false",
  "npm ci --omit=dev --prefer-offline --no-audit --no-fund"
]

[phases.build]
cmds = [
  "echo 'Build phase completed - no build step required'"
]

[start]
cmd = "node server.js"

[staticAssets]
"public" = "/"
