# .nixpacks.toml
[node]
version = "22"

[phases.install]
# Use npm install to avoid strict lockfile integrity checks for now
cmds = ["npm install --omit=dev"]

[phases.build]
cmds = []  # Express API, no build step

[start]
cmd = "node server.js"
