# .nixpacks.toml
[node]
version = "22"

[phases.install]
cmds = [
  "npm config set prefer-online true",
  "npm config set cache /tmp/.npm --location=global",
  "npm cache clean --force || true",
  "npm install --omit=dev --no-audit --no-fund"
]

[phases.build]
cmds = []

[start]
cmd = "node server.js"
