# .nixpacks.toml
[variables]
NODE_ENV = "production"

[phases.setup]
nixPkgs = ["nodejs_18", "npm-9_x"]

[phases.install]
cmds = [
  "npm config set fund false",
  "npm config set audit false", 
  "npm ci --only=production --no-optional"
]

[phases.build]
cmds = []

[start]
cmd = "node server.js"

[staticAssets]
"public" = "/"
